/** The film detail page keeps Om's personal response empty until Om supplies it. */
import { ArrowLeft, Clapperboard, Film, Music2, Ticket, Volume2 } from "lucide-react";
import { Link, useParams } from "wouter";
import SiteShell from "@/components/SiteShell";
import { findFilm, findSongById } from "@/lib/content";

export default function FilmDetail() {
  const { slug } = useParams<{ slug: string }>();
  const film = findFilm(slug);
  if (!film) return <SiteShell pageTheme="cinephile"><section className="film-reading film-reading--missing"><p className="section-kicker">screening not found</p><h1>This ticket<br />leads nowhere.</h1><p>The note may be a draft, or the address may have changed.</p><Link className="ink-button" href="/cinephile"><ArrowLeft size={16} /> Back to Cinephile</Link></section></SiteShell>;
  const nearbyTracks = (film.relatedSongIds ?? []).map((id) => findSongById(id)).filter((song): song is NonNullable<typeof song> => Boolean(song));
  const playTrack = (id: string, title: string, source?: string) => { if (source) window.dispatchEvent(new CustomEvent("creator-studio:play-release", { detail: { id, title, source, label: "screening mix" } })); };
  return <SiteShell pageTheme="cinephile"><article className="film-reading"><Link className="film-reading__back" href="/cinephile"><ArrowLeft size={16} /> back to the screening shelf</Link><header className="film-reading__header"><p className="section-kicker"><Film size={14} /> personal film journal</p>{film.isTemplate && <p className="illustrative-label illustrative-label--inline">screening folder · held open</p>}<h1>{film.title}</h1><p className="film-reading__metadata"><span>{film.director}</span><span>{film.year}</span><span>{film.watchedOn}</span></p></header><div className="film-reading__poster-slot"><div className="film-reading__sprockets" aria-hidden="true" /><span>an image from<br />the screening<br />can rest here</span><b>no. 01</b></div><section className="film-reading__body"><aside><Ticket size={27} /><span>personal<br />screening<br />note</span></aside><div><div className="film-reading__section"><p className="film-reading__label">what stayed with me</p><h2>{film.whatStayedWithMe}</h2></div><div className="film-reading__section"><p className="film-reading__label">my review</p><p>{film.review}</p></div><div className="film-reading__section film-reading__section--scene"><Clapperboard size={21} /><p className="film-reading__label">scene to remember</p><p>{film.sceneToRemember}</p></div><div className="film-reading__tags">{film.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></section>{nearbyTracks.length > 0 && <section className="film-reading__crossfade"><p className="section-kicker"><Music2 size={14} /> soundtrack crossfade</p><h2>A sound kept<br /><em>near the folder.</em></h2><p>{film.crossfadeNote}</p><div>{nearbyTracks.map((track) => <button key={track.id} onClick={() => playTrack(track.id, track.title, track.audioPreview)} type="button"><Volume2 size={16} /> {track.title}</button>)}</div></section>}</article></SiteShell>;
}
