import { ArrowUpRight, Download, FileText, Printer, Sparkles } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import { contactDetails, pressKit } from "@/lib/content";

function buildPressText() { return `${pressKit.creator}\n${pressKit.role}\n${pressKit.archiveName}\n\n${pressKit.shortBio}\n\nARCHIVE FOCUS\n${pressKit.focus.map((item) => `• ${item}`).join("\n")}\n\nSELECTED ROOMS\n${pressKit.selectedRoutes.map((item) => `• ${item.label}`).join("\n")}\n\nCONTACT\n${contactDetails.email || "Contact route: Creator Studio / Say hello"}\n`; }
function downloadPressNote() { const blob = new Blob([buildPressText()], { type: "text/plain" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "om-nandurkar-creator-studio-press-note.txt"; link.click(); URL.revokeObjectURL(url); }
function printPressSheet() { const sheet = window.open("", "_blank", "noopener,noreferrer"); if (!sheet) return; sheet.document.write(`<html><head><title>Press sheet · ${pressKit.creator}</title><style>body{font-family:Georgia,serif;padding:52px;color:#20252f;max-width:720px}h1{font-size:44px;margin:18px 0 4px}h2{font-size:15px;letter-spacing:.08em;margin-top:40px;text-transform:uppercase}p,li{font-size:18px;line-height:1.55}small{font-family:Arial,sans-serif;letter-spacing:.08em}</style></head><body><small>CREATOR STUDIO / PRESS SHEET</small><h1>${pressKit.creator}</h1><p>${pressKit.role}</p><h2>Short note</h2><p>${pressKit.shortBio}</p><h2>Archive focus</h2><ul>${pressKit.focus.map((item) => `<li>${item}</li>`).join("")}</ul><h2>Selected rooms</h2><ul>${pressKit.selectedRoutes.map((item) => `<li>${item.label}</li>`).join("")}</ul><h2>Contact</h2><p>${contactDetails.email || "Creator Studio / Say hello"}</p></body></html>`); sheet.document.close(); sheet.focus(); sheet.print(); }
export default function PressKit() { return <SiteShell pageTheme="about"><section className="press-hero"><p className="section-kicker"><FileText size={14} /> press kit / a small drawer</p><h1>For the rooms<br />that need a <em>clear note.</em></h1><p>A concise starting point for profiles, features, conversations, and selected archive references.</p><div><button onClick={printPressSheet} type="button"><Printer size={16} /> print press sheet</button><button onClick={downloadPressNote} type="button"><Download size={16} /> download press note</button></div></section><section className="press-profile"><article><p className="section-kicker"><Sparkles size={14} /> artist note</p><h2>{pressKit.creator}</h2><strong>{pressKit.role}</strong><p>{pressKit.shortBio}</p></article><aside><span>archive focus</span>{pressKit.focus.map((item, index) => <p key={item}>0{index + 1} / {item}</p>)}</aside></section><section className="press-selects"><div><p className="section-kicker">selected rooms</p><h2>Start at the<br /><em>door that fits.</em></h2><p>These routes offer a clear way into the archive, without turning a personal record into a list of claims.</p></div><div>{pressKit.selectedRoutes.map((room, index) => <Link key={room.route} href={room.route}><span>0{index + 1}</span><strong>{room.label}</strong><ArrowUpRight size={17} /></Link>)}</div></section><section className="press-materials"><div><p className="section-kicker">press materials</p><h2>Images and<br />details, <em>filed slowly.</em></h2><p>Approved portrait images, release artwork, and longer materials can be kept here when they are ready to travel with the archive.</p></div><div className="press-materials__mat"><span>press image / future filing</span><i /><i /><i /><small>No approved press images are filed yet.</small></div></section><section className="press-contact"><h2>Need another<br /><em>detail?</em></h2><p>The correspondence room is open for the conversations that need more than a short sheet.</p><Link className="ink-button" href="/contact">say hello <ArrowUpRight size={16} /></Link></section></SiteShell>; }
